export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';
export const ADD_POST_RESET = 'ADD_POST_RESET';

export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL';

export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';
export const GET_POST_RESET = 'GET_POST_RESET';

export const ADD_ACCEPTED_USER_REQUEST = 'ADD_ACCEPTED_USER_REQUEST';
export const ADD_ACCEPTED_USER_SUCCESS = 'ADD_ACCEPTED_USER_SUCCESS';
export const ADD_ACCEPTED_USER_FAIL = 'ADD_ACCEPTED_USER_FAIL';

export const REMOVE_ACCEPTED_USER_REQUEST = 'REMOVE_ACCEPTED_USER_REQUEST';
export const REMOVE_ACCEPTED_USER_SUCCESS = 'REMOVE_ACCEPTED_USER_SUCCESS';
export const REMOVE_ACCEPTED_USER_FAIL = 'REMOVE_ACCEPTED_USER_FAIL';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const GET_USER_POSTS_REQUEST = 'GET_USER_POSTS_REQUEST';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_FAIL = 'GET_USER_POSTS_FAIL';

export const MARK_POST_AS_COMPLETED_REQUEST = 'MARK_POST_AS_COMPLETED_REQUEST';
export const MARK_POST_AS_COMPLETED_SUCCESS = 'MARK_POST_AS_COMPLETED_SUCCESS';
export const MARK_POST_AS_COMPLETED_FAIL = 'MARK_POST_AS_COMPLETED_FAIL';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';
