// export const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST';
// export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
// export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL';



// export const USER_LOGOUT = 'USER_LOGOUT';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const GET_PROFILE_RESET = 'GET_PROFILE_RESET';

export const GET_ALL_PROFILES_REQUEST = 'GET_ALL_PROFILES_REQUEST';
export const GET_ALL_PROFILES_SUCCESS = 'GET_ALL_PROFILES_SUCCESS';
export const GET_ALL_PROFILES_FAIL = 'GET_ALL_PROFILES_FAIL';

export const UPLOAD_USER_IMAGE_REQUEST = 'UPLOAD_USER_IMAGE_REQUEST';
export const UPLOAD_USER_IMAGE_SUCCESS = 'UPLOAD_USER_IMAGE_SUCCESS';
export const UPLOAD_USER_IMAGE_FAIL = 'UPLOAD_USER_IMAGE_FAIL';

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';

export const EDIT_PROFILE_PREFERENCES_REQUEST = 'EDIT_PROFILE_PREFERENCES_REQUEST';
export const EDIT_PROFILE_PREFERENCES_SUCCESS = 'EDIT_PROFILE_PREFERENCES_SUCCESS';
export const EDIT_PROFILE_PREFERENCES_FAIL = 'EDIT_PROFILE_PREFERENCES_FAIL';


export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';

// export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
// export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
// export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

// export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
// export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
// export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

// export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
// export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
// export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

// export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
// export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
// export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
// export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

// export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
// export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
// export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
// export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

// export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
// export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
// export const USER_LIST_FAIL = 'USER_LIST_FAIL';
// export const USER_LIST_RESET = 'USER_LIST_RESET';

// export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
// export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
// export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

// export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
// export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
// export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
// export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';
